name: Auto Generate Release Log

on:
    workflow_dispatch:
        inputs:
            tag_name:
              required: true
              type: string
            previous_tag_name:
              required: true
              type: string
            target_commitish:
              required: true
              type: string

permissions: 
    contents: write    
          
jobs:
  generate_release_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
            go-version: '1.20.2'
      - name: Get release note
        id: get_release_note
        run: |
            set -e
            echo "response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Yunxe/auto-release-demo/releases/generate-notes \
            -d '{"tag_name":"${{inputs.tag_name}}","target_commitish":"${{inputs.target_commitish}}","previous_tag_name":"${{inputs.previous_tag_name}}"}')" >> "$GITHUB_OUTPUT"
      - name: Run Go Program
        run: |
              echo ${{ steps.get_release_note.outputs.response }}
              go run cmd/gpt/gpt.go "${{ steps.get_release_note.outputs.response }}"
        env:
            AZURE_OPENAI_APIKEY: ${{ secrets.AZURE_OPENAI_APIKEY }}
            AZURE_OPENAI_HOST: ${{ secrets.AZURE_OPENAI_HOST }}
      - name: Display Changelog Contents
        run: cat CHANGELOG/CHANGELOG-v0.2.0.md | echo
    