name: Auto Generate Release Log

on:
    workflow_dispatch:
        inputs:
            tag_name:
              required: true
              type: string
            previous_tag_name:
              required: true
              type: string
            target_commitish:
              required: true
              type: string

permissions: 
    contents: write    
          
jobs:
  generate_release_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
            go-version: '1.20.2'

      - name: Get release note
        run: |
            set -e
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Yunxe/auto-release-demo/releases/generate-notes \
            -d '{"tag_name":"${{inputs.tag_name}}","target_commitish":"${{inputs.target_commitish}}","previous_tag_name":"${{inputs.previous_tag_name}}"}'
            echo "::set-output name=release-note::$release-note"
      - name: Run Go Program
        run: |
            go run cmd/gpt/gpt.go "${{ steps.get_release_note.outputs.release-note }}"

      - name: Display Changelog Contents
        run: cat CHANGELOG/CHANGELOG-v0.2.0.md | echo
          
    #   - name: Save Release Log as Artifact
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: release-log
    #       path: release_log.md
